/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dbtest.model;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class ProductRepository {
    private Connection conn;

    public ProductRepository(Connection conn){
        this.conn = conn;
    }

    public void insert(String name, int price, int qty) throws SQLException {

        // 2. 버퍼 연결
        String sql = "insert into product(name, price, qty, created_at) values(?,?,?,now())";
        PreparedStatement pstmt = conn.prepareStatement(sql);

        // 3. 물음표 완성
        pstmt.setString(1, name);
        pstmt.setInt(2, price);
        pstmt.setInt(3, qty);

        // 4. 전송
        int result = pstmt.executeUpdate();

        // 5. 응답에 대한 처리
        if (result == 1) {
            System.out.println("insert 성공");
        } else {
            System.out.println("insert 실패");
        }
        pstmt.close();
    }
}
